server:
  port: 8080

spring:
  application:
    name: eventos
  datasource:
    url: jdbc:mysql://localhost:3306/evento_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

